name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/teste_docker:latest \
          --build-arg NODE_ENV=${{ secrets.NODE_ENV }} \
          --build-arg PORT=${{ secrets.PORT }} \
          --build-arg POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
          --build-arg POSTGRES_PORT=${{ secrets.POSTGRES_PORT}} \
          --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          --build-arg POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} .
          docker push $DOCKER_USERNAME/teste_docker:latest
